INSERT INTO doktor VALUES ('36903191164', 'Hilmi', 'Kunter', 'Harran Universitesi Tip Fakultesi', 'Uzm.', 'Halk Sagligi', 'TOBB ETU Hastanesi');
INSERT INTO doktor VALUES ('89373904794', 'Huccet', 'Kocoglu', 'Ataturk Universitesi Tip Fakultesi', 'Op.', 'Noroloji', 'Bestepe Devlet Hastanesi');
INSERT INTO doktor VALUES ('83447698078', 'Tamer', 'Kocoglu', 'Firat Universitesi Tip Fakultesi', 'Doc.', 'Cocuk Sagligi ve Hastaliklari', 'Ozel Doruk Bursa Hastanesi');
INSERT INTO doktor VALUES ('36828438355', 'Semra', 'Ayverdi', 'Usak Universitesi Tip Fakultesi', 'Op.', 'Goz Hastaliklari', 'Acibadem Bursa');
INSERT INTO doktor VALUES ('90967223836', 'Muktedir', 'Kucukler', 'Duzce Universitesi Tip Fakultesi', 'Doc.', 'Fiziksel Tip ve Rehabilitasyon', 'Medicana Ankara');
INSERT INTO doktor VALUES ('52478976245', 'Pervin', 'Tunceri', 'Yozgat Bozok Universitesi Tip Fakultesi', 'Uzm.', 'Goz Hastaliklari', 'Bestepe Devlet Hastanesi');
INSERT INTO doktor VALUES ('85884641463', 'Hande', 'Tunceri', 'Yozgat Bozok Universitesi Tip Fakultesi', 'Prt.', 'Radyoloji', 'Ozel Doruk Bursa Hastanesi');
INSERT INTO doktor VALUES ('43084601292', 'Melis', 'Ayverdi', 'Akdeniz Universitesi Tip Fakultesi', 'Uzm.', 'Ic Hastaliklari', 'Ozel Doruk Bursa Hastanesi');
INSERT INTO doktor VALUES ('50789149033', 'Yaprak', 'Oraloglu', 'Siirt Universitesi Tip Fakultesi', 'Prt.', 'Kalp ve Damar Cerrahisi', 'Medicana Ankara');
INSERT INTO doktor VALUES ('65219842481', 'Zumrut', 'Tunceri', 'Akdeniz Universitesi Tip Fakultesi', 'Prof.', 'Anatomi', 'Medicana Ankara');
INSERT INTO doktor VALUES ('27370313090', 'Cagil', 'Kocoglu', 'Giresun Universitesi Tip Fakultesi', 'Op.', 'Tibbi Patoloji', 'Ozel Doruk Bursa Hastanesi');
INSERT INTO doktor VALUES ('57558589072', 'Naim', 'Tunceri', 'Aksaray Universitesi Tip Fakultesi', 'Uzm.', 'Dermatoloji', 'Acibadem Bursa');
INSERT INTO doktor VALUES ('60342446575', 'Kerim', 'Kucukler', 'Cukurova Universitesi Tip Fakultesi', 'Prt.', 'Tip Egitimi', 'Medicana Ankara');
INSERT INTO doktor VALUES ('74287790195', 'Nazli', 'Kocoglu', 'Trakya Universitesi Tip Fakultesi', 'Op.', 'Goz Hastaliklari', 'Acibadem Bursa');
INSERT INTO doktor VALUES ('46012524913', 'Pelinsu', 'Ayverdi', 'Karabuk Universitesi Tip Fakultesi', 'Yrd. Doc.', 'Psikiyatri', 'Acibadem Bursa');
INSERT INTO doktor VALUES ('53576775001', 'Barkin', 'Tunceri', 'Adiyaman Universitesi Tip Fakultesi', 'Uzm.', 'Radyoloji', 'Acibadem Bursa');
INSERT INTO doktor VALUES ('24294218646', 'Hilal', 'Ayverdi', 'Sakarya Universitesi Tip Fakultesi', 'Uzm.', 'Tip Egitimi', 'Bestepe Devlet Hastanesi');
INSERT INTO doktor VALUES ('19376438065', 'Ramiz', 'Kocoglu', 'Giresun Universitesi Tip Fakultesi', 'Prt.', 'Fiziksel Tip ve Rehabilitasyon', 'Medicana Ankara');
INSERT INTO doktor VALUES ('20367779119', 'Sahin', 'Ayverdi', 'Aksaray Universitesi Tip Fakultesi', 'Op.', 'Tibbi Mikrobiyoloji', 'Ozel Doruk Bursa Hastanesi');
INSERT INTO doktor VALUES ('35704287382', 'Ayhan', 'Ayverdi', 'Balikesir Universitesi Tip Fakultesi', 'Doc.', 'Anatomi', 'Acibadem Bursa');
INSERT INTO doktor VALUES ('72090728059', 'Isin', 'Kucukler', 'Ege Universitesi Tip Fakultesi', 'Yrd. Doc.', 'Cocuk Cerrahisi', 'Medicana Ankara');
INSERT INTO doktor VALUES ('47061155704', 'Ezrak', 'Ayverdi', 'Firat Universitesi Tip Fakultesi', 'Prt.', 'Kulak Burun Bogaz', 'Medicana Ankara');
INSERT INTO doktor VALUES ('16085141868', 'Temel', 'Kocoglu', 'Erciyes Universitesi Tip Fakultesi', 'Prof.', 'Tibbi Farmakoloji', 'Bestepe Devlet Hastanesi');
INSERT INTO doktor VALUES ('69548844779', 'Atif', 'Kucukler', 'Kocaeli Universitesi Tip Fakultesi', 'Yrd. Doc.', 'Fiziksel Tip ve Rehabilitasyon', 'Acibadem Bursa');
INSERT INTO doktor VALUES ('54772603740', 'Ozer', 'Tunceri', 'Kocaeli Universitesi Tip Fakultesi', 'Uzm.', 'Cocuk Sagligi ve Hastaliklari', 'Medicana Ankara');
INSERT INTO doktor VALUES ('98891094405', 'Kubat', 'Kucukler', 'Adiyaman Universitesi Tip Fakultesi', 'Uzm.', 'Immunoloji', 'Bestepe Devlet Hastanesi');
INSERT INTO doktor VALUES ('69413263888', 'Agca', 'Kunter', 'Kirikkale Universitesi Tip Fakultesi', 'Prt.', 'Acil Tip', 'Acibadem Bursa');
INSERT INTO doktor VALUES ('25861159186', 'Lamih', 'Kunter', 'Ordu Universitesi Tip Fakultesi', 'Yrd. Doc.', 'Kulak Burun Bogaz', 'TOBB ETU Hastanesi');
INSERT INTO doktor VALUES ('56077620438', 'Yildiz', 'Kucukler', 'Kafkas Universitesi Tip Fakultesi', 'Yrd. Doc.', 'Acil Tip', 'Acibadem Bursa');
INSERT INTO doktor VALUES ('56577754962', 'Belcim', 'Kucukler', 'Adiyaman Universitesi Tip Fakultesi', 'Prof.', 'Gogus Cerrahisi', 'Medicana Ankara');